baseURL = 'https://ostensible-paradox.pages.dev/'
title = 'My Hugo Project'
theme = 'PaperMod'
timezone = 'UTC'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

[permalinks]

[module]
  [[module.mounts]]
    source = 'content/treehouse'
    target = 'content/treehouse'
    lang = 'zh'

  [[module.mounts]]
    source = 'content/treehouse'
    target = 'content/treehouse'
    lang = 'en'

  [[module.mounts]]
    source = 'content/Chinese'
    target = 'content'
    lang = 'zh'

  [[module.mounts]]
    source = 'content/English'
    target = 'content'
    lang = 'en'

  [[module.mounts]]
    source = 'data'
    target = 'data'

  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'

  [[module.mounts]]
    source = 'i18n'
    target = 'i18n'

  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'

  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    source = 'static'
    target = 'static'

[params]
  env = "production"
  mainSections = ["posts"]
  defaultTheme = "auto"
  ShowThemeToggleButton = true
  DateFormat = "Monday, 15:04, 2006-01-02"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowFullTextinRSS = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
  math = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

  [params.assets]
    favicon = "<link / abs url>"
    favicon16x16 = "<link / abs url>"
    favicon32x32 = "<link / abs url>"
    apple_touch_icon = "<link / abs url>"
    safari_pinned_tab = "<link / abs url>"

  [params.label]
    text = "Home"

  [params.profileMode]
    enabled = false
    title = "ExampleSite"
    subtitle = "This is subtitle"
    imageUrl = "<profile image url>"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "Tags"
      url = "tags"

  [params.homeInfoParams]
    Title = "Hi there \U0001F44B"
    Content = "您可以使用 Markdown Lovejade 来将飞书文档转为markdown。"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/OstensibleParadox"

[languages]
  [languages.zh]
    label = '中文'
    locale = 'zh-cn'
    weight = 1

    [[languages.zh.menu.main]]
      identifier = "search"
      name = "搜索"
      url = "/search/"
      weight = 5

    [[languages.zh.menu.main]]
      identifier = "home"
      name = "首页"
      url = "/"
      weight = 10

    [[languages.zh.menu.main]]
      identifier = "posts"
      name = "文章"
      url = "/posts/"
      weight = 20

    [[languages.zh.menu.main]]
      parent = "posts"
      name = "学术论文"
      url = "/categories/学术论文/"
      weight = 1

    [[languages.zh.menu.main]]
      parent = "posts"
      name = "思路与探索"
      url = "/categories/思路与探索/"
      weight = 2

    [[languages.zh.menu.main]]
      parent = "posts"
      name = "个人日志"
      url = "/categories/个人日志/"
      weight = 3

    [[languages.zh.menu.main]]
      parent = "posts"
      name = "艺术创想"
      url = "/categories/艺术创想/"
      weight = 4

    [[languages.zh.menu.main]]
      identifier = "us"
      name = "小露的树屋"
      url = "/treehouse/"
      weight = 25

    [[languages.zh.menu.main]]
      identifier = "about"
      name = "关于"
      url = "/about/"
      weight = 30

  [languages.en]
    label = 'English'
    locale = 'en-us'
    weight = 2

    [[languages.en.menu.main]]
      identifier = "search"
      name = "Search"
      url = "/search/"
      weight = 5

    [[languages.en.menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 10

    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
      weight = 20

    [[languages.en.menu.main]]
      parent = "posts"
      name = "Academic Papers"
      url = "/categories/academic-papers/"
      weight = 1

    [[languages.en.menu.main]]
      parent = "posts"
      name = "Explorative Thoughts"
      url = "/categories/explorative-thoughts/"
      weight = 2

    [[languages.en.menu.main]]
      parent = "posts"
      name = "My Daily Logs"
      url = "/categories/my-daily-logs/"
      weight = 3

    [[languages.en.menu.main]]
      parent = "posts"
      name = "Arts & Creative"
      url = "/categories/arts-creative/"
      weight = 4

    [[languages.en.menu.main]]
      identifier = "us"
      name = "Lucia's Treehouse"
      url = "/treehouse/"
      weight = 25

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 30

[markup.goldmark.renderer]
  unsafe = true
