name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 如果使用 Git 子模块（如主题），需要递归检出
          fetch-depth: 0         # 获取完整历史记录，用于 Hugo 的 GitInfo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'  # 使用最新版本的 Hugo
          extended: true         # 需要扩展版以支持 SCSS/SASS

      - name: Build
        run: hugo --minify  # 构建网站并压缩资源

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Hugo 默认输出目录

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
